### ISSUE TITLE
unparsed adress [0] error

### ISSUE THREAD

**Issue by pembo210** [pembo210/Dogecore#1]
link - http://moonblocks.com:2000/tx/ea09f47a395af7e2b68da54481f69603263176815e5dc4ae5744bdbed750ca99

**Comment by plncoin** [comment]
pembo, please give me your e-mail address :)

**Comment by pembo210** [comment]
pembo210
gmail
u want a plncoin version?

**Comment by plncoin** [comment]
Yes, we wont this

**Comment by plncoin** [comment]
And how?
